version: 0.2

env:
  variables:
    PROJECT_BUILD_IMAGE_NAME: "242906888793.dkr.ecr.us-east-1.amazonaws.com/vgrischenko-fronend"
    PROJECT_BUILD_VERSION: "latest"
    PROJECT_BUILD_IMAGE_ENV: "-master"
  parameter-store:
    API_URL: "/vgrischenko-frontend/dev/API_URL"
  exported-variables:
    - API_URL
    - PROJECT_BUILD_IMAGE_NAME
    - PROJECT_BUILD_VERSION
    - PROJECT_BUILD_IMAGE_ENV
    
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$PROJECT_BUILD_IMAGE_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - PROJECT_BUILD_IMAGE_VERSION=${COMMIT_HASH:=latest}
      - IMAGE_TAG=$PROJECT_BUILD_IMAGE_VERSION$PROJECT_BUILD_IMAGE_ENV
      - IMAGE_LATEST_TAG=$PROJECT_BUILD_VERSION$PROJECT_BUILD_IMAGE_ENV
      - echo $IMAGE_LATEST_TAG
      - echo $IMAGE_TAG
      - DOCKER_PATH="."
  build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Build started on `date`
      - echo $PWD
      - ls -la
      - echo $DOCKER_PATH
      - cd $DOCKER_PATH
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_LATEST_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_LATEST_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker image ls
      - docker push $REPOSITORY_URI:$IMAGE_LATEST_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo $PWD
      - cd $CODEBUILD_SRC_DIR
      - echo $PWD
      - echo Writing image definitions file...
      - printf '[{"name":"vgrischenko-frontend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_LATEST_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
